@startuml
class WeatherForecastController {
    + WeatherForecastController(logger:ILogger<WeatherForecastController>)
    + Get() : IEnumerable<WeatherForecast>
}
ControllerBase <|-- WeatherForecastController
@enduml
